### ISSUE TITLE
Feature Request:  Column Names provided in the dataset documentation

### ISSUE THREAD

**Issue by bms63** [pharmaverse/pharmaversesdtm#125] opened 2024-09-30 00:07 UTC
### Feature Idea

Could we have a list of the columns available in the dataset?  I don't feel like loading them and doing colnames(data) cuz im lazy...
![image](https://github.com/user-attachments/assets/8fac6e70-58a9-4311-8e4d-b129fa2ae86d)

**Comment by manciniedoardo** [comment] 2024-10-25 07:01
Will look into it for next release @bms63

**Comment by manciniedoardo** [comment] 2024-10-25 07:13
Duplicate of #111

**Closed by manciniedoardo** 2024-10-25 07:13 UTC
Labels: enhancement
